meta_product_name: "Join2Kick"
meta_title: "Join2Kick - We bring clubs and players together!"
meta_description: "Smart Recruting with Join2Kick. Social Media Recruitment with Join2Kick offers you as club owner effectively scout potential players based on your needs"
meta_image: "Logo.png" # should exist in `app/assets/images/`

